language: c

jobs:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    # gcc is just a link to clang on OS X so no need to run it without
    # sanitizers
    - os: osx
      compiler: gcc
      env: CONFIGURE_EXTRA=--with-sanitize=basic
    - os: osx
      compiler: clang

env:
  global:
    - secure: "Ejc9hqPE/TQ1HiSao3FHZ8piTmpCVuQthPYUuFv8Yz7GDbia7yx85b9IHd17wVmg1rGHaFed9hvSesbfFu82h86NYLmnQJGvA4XAptpBw8Z3621U0ar2QXHuaY7uAaKdeAC5NwIS6/DiufEqGtQJrNNs+5pLEATGOuoO+QugdTI="

addons:
  apt:
    packages:
      - python-pip
  coverity_scan:
    project:
      name: vifm/vifm
      version: 0.10.1+
      description: "TUI file manager with vi like key bindings."
    notification_email: xaizek@posteo.net
    build_command_prepend: scripts/fix-timestamps fast && ./configure --disable-dependency-tracking
    build_command: make -j 3
    branch_pattern: coverity-scan

cache:
  - pip

script:
 - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then
     scripts/fix-timestamps fast && (
       if [ "$CC" = gcc -a "$TRAVIS_OS_NAME" = linux ]; then
         pip install --user cpp-coveralls pyopenssl ndg-httpsclient pyasn1 &&
         ./configure --disable-dependency-tracking --enable-coverage;
       else
         ./configure --disable-dependency-tracking $CONFIGURE_EXTRA;
       fi
     ) &&
     make -j4 &&
     make check;
   fi

after_success:
 - if [ "$COVERITY_SCAN_BRANCH" != 1 -a "$CC" = gcc ]; then
     coveralls --encoding iso-8859-1 --build-root src/
                                     --exclude tests
                                     --exclude src/utils/parson.c
                                     --exclude src/utils/xxhash.c
                                     --gcov-options '\-p';
   fi

notifications:
  email:
    recipients:
      - xaizek@posteo.net
